export const translations = {
  en: {
    appTitle: "SmartBook AI",
    tagline: "Your trilingual personal AI Tutor & Library in your pocket",
    welcome: "Welcome to SmartBook AI",
    subWelcome: "Learn physics, math, and software engineering with a real-time smart tutor.",
    tabHome: "Home",
    tabBooks: "Books",
    tabVideos: "Videos",
    tabAiTutor: "AI Tutor",
    tabProfile: "Profile",
    tabAdmin: "Admin Console",
    searchPlaceholder: "Search courses, books, topics...",
    searchBtn: "Search",
    filterLang: "Language",
    filterType: "Price Type",
    all: "All",
    free: "Free",
    paid: "Paid",
    loginTitle: "Sign In",
    loginSub: "Access your personalized trilingual AI Tutor and books",
    emailLabel: "Email Address",
    passLabel: "Password",
    loginBtn: "Sign In",
    signupLink: "Don't have an account? Sign Up",
    loginLink: "Already have an account? Sign In",
    signupTitle: "Create Account",
    signupSub: "Get started on your AI-assisted learning journey",
    nameLabel: "Full Name",
    signupBtn: "Create Account",
    welcomeUser: "Welcome back,",
    myWallet: "Simulated Wallet",
    addFunds: "Add Funds (ETB)",
    addFundsBtn: "Add Funds",
    langSetting: "Application Language",
    logoutBtn: "Log Out",
    readNow: "Read Now",
    unlockBook: "Unlock Book",
    bookDetails: "Book Details",
    pages: "Pages",
    language: "Language",
    category: "Category",
    videoLecture: "Video Lectures",
    duration: "Duration",
    askAiPlaceholder: "Ask your AI Tutor anything in Oromoo, Amharic, or English...",
    send: "Send",
    clearHistory: "Clear Chat",
    tutorName: "AI Study Coach",
    speakingOn: "Voice Output: ON",
    speakingOff: "Voice Output: OFF",
    startListening: "Click to speak",
    stopListening: "Listening...",
    paymentRequired: "Telebirr Payment Required",
    paymentInstructions: "Enter your Telebirr mobile number to complete the purchase of this book.",
    telebirrPhone: "Telebirr Mobile Number (09...)",
    payNow: "Pay with Telebirr",
    verifying: "Verifying with Telebirr...",
    enterOtp: "Enter simulated Telebirr verification OTP sent to your phone",
    otpLabel: "OTP Code",
    otpHint: "Use '123456' for simulation success",
    confirmPayment: "Confirm Payment",
    paymentSuccess: "Payment Successful!",
    bookUnlocked: "This book is now permanently unlocked on your profile.",
    backToLibrary: "Back to Library",
    totalRevenue: "Simulated Net Revenue",
    totalUsers: "Registered Students",
    totalBooks: "Books in Library",
    totalVideos: "Uploaded Videos",
    adminTitle: "Admin Administration Console",
    addNewBook: "Upload New Book",
    addNewVideo: "Upload Video Lecture",
    bookTitle: "Book Title",
    bookDesc: "Book Description",
    bookPrice: "Price in ETB (0 if free)",
    bookUrl: "PDF Document Link (optional)",
    videoTitle: "Video Title",
    videoDesc: "Video Description",
    videoUrl: "Video URL (MP4 link)",
    videoDuration: "Duration (MM:SS)",
    uploadBtn: "Publish Content",
    transactionsHistory: "Simulated Merchant Activity Log",
    date: "Date",
    amount: "Amount",
    status: "Status",
    walletSim: "Ethio Telecom Simulated Wallet",
    oromo: "Afaan Oromoo",
    amharic: "አማርኛ",
    english: "English",
  },
  om: {
    appTitle: "SmartBook AI",
    tagline: "Kitaaba fi barsiisaa dhuunfaa AI Afaan sadiin kiisii keessan keessaa",
    welcome: "Baga Gara SmartBook AI Dhuftan",
    subWelcome: "Fiiziksii, herregaafi koodii barreessuu pirograamaa barsiisaa AI beekaa waliin baradhu.",
    tabHome: "Mana",
    tabBooks: "Kitaabota",
    tabVideos: "Viidiyoo",
    tabAiTutor: "AI Tutor",
    tabProfile: "Profaayilii",
    tabAdmin: "Admin Console",
    searchPlaceholder: "Kitaabota, barumsawwan, dhimmoota barbaadi...",
    searchBtn: "Barbaadi",
    filterLang: "Afaan",
    filterType: "Gatii",
    all: "Hunda",
    free: "Bilaasha",
    paid: "Kan Kafalamu",
    loginTitle: "Seeni",
    loginSub: "Barsiisaa dhuunfaa AI fi library keessan argachuuf seeni",
    emailLabel: "Imeelii",
    passLabel: "Jecha IcCitii (Password)",
    loginBtn: "Seeni",
    signupLink: "Herrega hin qabduu? Asitti banadhu",
    loginLink: "Herrega qabduu? Seeni",
    signupTitle: "Herrega Banadhu",
    signupSub: "Gara barumsa teeknoolojii AI jalqabuuf herrega uumi",
    nameLabel: "Maqaa Guutuu",
    signupBtn: "Uumi",
    welcomeUser: "Baga nagaan deebite,",
    myWallet: "Wallet Simulaasii",
    addFunds: "Maallaqa Dabali (ETB)",
    addFundsBtn: "Dabali",
    langSetting: "Afaan Appilikeeshinii",
    logoutBtn: "Ba'i (Logout)",
    readNow: "Dubbisi",
    unlockBook: "Kitaaba Bani",
    bookDetails: "Bal'ina Kitaabaa",
    pages: "Fuulota",
    language: "Afaan",
    category: "Ramaddii",
    videoLecture: "Barumsa Viidiyoo",
    duration: "Yeroo",
    askAiPlaceholder: "Barsiisaa AI keessan Afaan Oromoo, Amharic ykn English gaafadhaa...",
    send: "Ergi",
    clearHistory: "Qulqulleessi",
    tutorName: "AI Tutor Gargaaraa",
    speakingOn: "Sagalee Dubbisuu: BANAMEERA",
    speakingOff: "Sagalee Dubbisuu: DHAMSAMEERA",
    startListening: "Mic cuqi",
    stopListening: "Dhageeffachaa jira...",
    paymentRequired: "Kafaltii Telebirr Barbaachisa",
    paymentInstructions: "Kitaaba kana dubbisuuf lakkoofsa bilbila Telebirr keessan galchuun kafaltii xumuraa.",
    telebirrPhone: "Lakkoofsa Telebirr (09...)",
    payNow: "Kafali (Telebirr)",
    verifying: "Telebirr irraa mirkaneessaa jira...",
    enterOtp: "Koodii OTP simulaasii bilbila keessaniif ergame galchaa",
    otpLabel: "Koodii OTP",
    otpHint: "OTP '123456' fayyadamaa",
    confirmPayment: "Kafaltii Mirkaneessi",
    paymentSuccess: "Kafaltiin Milkaa'eera!",
    bookUnlocked: "Kitaabni kun profaayilii keessan irratti barabaraaf banameera.",
    backToLibrary: "Gara Library Deebi'i",
    totalRevenue: "Simulated Net Revenue",
    totalUsers: "Barattoota Galmeeffaman",
    totalBooks: "Kitaabota Library",
    totalVideos: "Viidiyoo Upload Ta'an",
    adminTitle: "Admin Console Bulchiinsaa",
    addNewBook: "Kitaaba Haaraa Upload Godhi",
    addNewVideo: "Viidiyoo Barumsaa Upload Godhi",
    bookTitle: "Mata duree Kitaabaa",
    bookDesc: "Ibsa Kitaabaa",
    bookPrice: "Gatii ETB (0 yoo bilaasha ta'e)",
    bookUrl: "PDF Link (optional)",
    videoTitle: "Mata duree Viidiyoo",
    videoDesc: "Ibsa Viidiyoo",
    videoUrl: "Video URL (MP4 link)",
    videoDuration: "Yeroo (MM:SS)",
    uploadBtn: "Maxxansi",
    transactionsHistory: "Seenaa Kafaltii Maamiltootaa",
    date: "Guyyaa",
    amount: "Gatii",
    status: "Haala",
    walletSim: "Simulaasii Wallet Ethio Telecom",
    oromo: "Afaan Oromoo",
    amharic: "አማርኛ",
    english: "English",
  },
  am: {
    appTitle: "SmartBook AI",
    tagline: "ባለ ሶስት ቋንቋ የግል AI አስተማሪ እና ቤተ-መጽሐፍት በኪስዎ ውስጥ",
    welcome: "ወደ SmartBook AI እንኳን በደህና መጡ",
    subWelcome: "ፊዚክስ፣ ሂሳብ እና የሶፍትዌር ኢንጂነሪንግን ከተለዋዋጭ የኤአይ አስተማሪዎ ጋር ይማሩ።",
    tabHome: "መነሻ",
    tabBooks: "መጽሐፍት",
    tabVideos: "ቪዲዮዎች",
    tabAiTutor: "የኤአይ አስተማሪ",
    tabProfile: "ፕሮፋይል",
    tabAdmin: "የአስተዳዳሪ ክፍል",
    searchPlaceholder: "መጽሐፍት፣ ትምህርቶች፣ አርእስቶች ፈልግ...",
    searchBtn: "ፈልግ",
    filterLang: "ቋንቋ",
    filterType: "የዋጋ አይነት",
    all: "ሁሉም",
    free: "ነፃ",
    paid: "የሚከፈልበት",
    loginTitle: "ግባ",
    loginSub: "የእርስዎን ግላዊ የኤአይ አስተማሪ እና መጽሐፍት ለማግኘት ይግቡ",
    emailLabel: "የኢሜል አድራሻ",
    passLabel: "የይለፍ ቃል",
    loginBtn: "ግባ",
    signupLink: "አካውንት የለዎትም? ይመዝገቡ",
    loginLink: "አካውንት አለዎት? ይግቡ",
    signupTitle: "አዲስ አካውንት መፍጠር",
    signupSub: "በባለሙያ የኤአይ የታገዘ የትምህርት ጉዞዎን ዛሬ ይጀምሩ",
    nameLabel: "ሙሉ ስም",
    signupBtn: "ይመዝገቡ",
    welcomeUser: "እንኳን ደህና መጡ፣",
    myWallet: "ሲሙሌትድ የገንዘብ ቦርሳ",
    addFunds: "ገንዘብ ጨምር (ETB)",
    addFundsBtn: "ጨምር",
    langSetting: "የመተግበሪያ ቋንቋ",
    logoutBtn: "ውጣ (Log Out)",
    readNow: "አሁን አንብብ",
    unlockBook: "መጽሐፍ ክፈት",
    bookDetails: "የመጽሐፍ ዝርዝር",
    pages: "ገጾች",
    language: "ቋንቋ",
    category: "ምድብ",
    videoLecture: "የቪዲዮ ትምህርቶች",
    duration: "ርዝመት",
    askAiPlaceholder: "የኤአይ አስተማሪዎን በኦሮምኛ፣ በአማርኛ ወይም በእንግሊዝኛ ይጠይቁ...",
    send: "ላክ",
    clearHistory: "ውይይት አጽዳ",
    tutorName: "AI ጥናት ረዳት",
    speakingOn: "ድምጽ ማንበቢያ: በርቷል",
    speakingOff: "ድምጽ ማንበቢያ: ጠፍቷል",
    startListening: "ለመናገር ይጫኑ",
    stopListening: "እያዳመጥኩ ነው...",
    paymentRequired: "የቴሌብር ክፍያ ይጠየቃል",
    paymentInstructions: "ይህንን መጽሐፍ ለመክፈት እባክዎ የቴሌብር ስልክ ቁጥርዎን ያስገቡ።",
    telebirrPhone: "የቴሌብር ስልክ ቁጥር (09...)",
    payNow: "በቴሌብር ክፈል",
    verifying: "ከቴሌብር ጋር በመገናኘት ላይ...",
    enterOtp: "ወደ ስልክዎ የተላከውን የቴሌብር ሲሙሌሽን ማረጋገጫ OTP ኮድ ያስገቡ",
    otpLabel: "የ OTP ኮድ",
    otpHint: "ለሲሙሌሽን ማለፊያ '123456' ይጠቀሙ",
    confirmPayment: "ክፍያውን አረጋግጥ",
    paymentSuccess: "ክፍያው ተሳክቷል!",
    bookUnlocked: "ይህ መጽሐፍ አሁን በመገለጫዎ ላይ በቋሚነት ተከፍቷል።",
    backToLibrary: "ወደ ቤተ-መጽሐፍት ተመለስ",
    totalRevenue: "ጠቅላላ ገቢ (ሲሙሌሽን)",
    totalUsers: "የተመዘገቡ ተማሪዎች",
    totalBooks: "ያሉ መጽሐፍት",
    totalVideos: "የተጫኑ ቪዲዮዎች",
    adminTitle: "የአስተዳዳሪ ቁጥጥር ክፍል",
    addNewBook: "አዲስ መጽሐፍ መጫኛ",
    addNewVideo: "አዲስ የቪዲዮ ትምህርት መጫኛ",
    bookTitle: "የመጽሐፍ ርዕስ",
    bookDesc: "የመጽሐፍ ማብራሪያ",
    bookPrice: "ዋጋ በብር (ነፃ ከሆነ 0 ያስገቡ)",
    bookUrl: "ፒዲኤፍ ሊንክ (አማራጭ)",
    videoTitle: "የቪዲዮ ርዕስ",
    videoDesc: "የቪዲዮ ማብራሪያ",
    videoUrl: "የቪዲዮ URL (MP4 ሊንክ)",
    videoDuration: "ርዝመት (ደቂቃ:ሰከንድ)",
    uploadBtn: "አትም",
    transactionsHistory: "የደንበኞች የክፍያ ታሪክ ማህደር",
    date: "ቀን",
    amount: "ዋጋ",
    status: "ሁኔታ",
    walletSim: "የኢትዮ ቴሌኮም የክፍያ መተግበሪያ (ሲሙሌሽን)",
    oromo: "Afaan Oromoo",
    amharic: "አማርኛ",
    english: "English",
  }
};
